# Generated by Django 4.2.2 on 2023-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ols_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='desc',
            new_name='card_desc',
        ),
        migrations.AddField(
            model_name='course',
            name='card_image',
            field=models.ImageField(default=1, upload_to='uploads/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/file/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/', verbose_name='video'),
        ),
    ]
