# Generated by Django 4.2.2 on 2023-10-03 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ols_app', '0002_rename_desc_course_card_desc_course_card_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='source_file',
        ),
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ols_app.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
