# Generated by Django 4.2.2 on 2023-09-25 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ols_app', '0002_rename_desc_course_card_desc_course_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
