# Generated by Django 4.2.2 on 2023-10-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ols_app', '0003_remove_course_source_file_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_image',
            field=models.FileField(upload_to='uploads/images/'),
        ),
    ]
