# Generated by Django 4.2.2 on 2023-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ols_app', '0005_remove_course_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/file/'),
        ),
    ]
