# Generated by Django 4.2.2 on 2023-10-04 07:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ols_app', '0006_alter_filefield_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
    ]
