# Generated by Django 4.2.2 on 2023-10-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ols_app', '0007_course_content_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='paragraph',
        ),
    ]
