# Generated by Django 4.2.2 on 2023-09-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ols_app', '0008_alter_course_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='paragraph',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
